name: CI text scrambling

on:
  push:
    branches: [ master, main ]
    tags: [ "**" ]
    paths:
      - text-scrambling/**
      - .github/workflows/ci-text-scrambling.yml
  pull_request:
    branches: [ "**" ]
    paths:
      - text-scrambling/**
      - .github/workflows/ci-text-scrambling.yml

jobs:
  Check-text-scrambling:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@master

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        working-directory: text-scrambling 
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -e .[dev]

      - name: Run precommit
        working-directory: text-scrambling
        run: python3 precommit.py
